In [9]:
# Loading in the pandas module
import pandas as pd

# Reading results file
results = pd.read_csv('~/Workspace/issue-crawler/rscripts/results/20181104084742-long_live_bug-evaluation.csv')
results.head(10)

,Dataset,Model,Threshold,Train_Size,Train_Qt_Class_0,Train_Qt_Class_1,Test_Size,Test_Qt_Class_0,Test_Qt_Class_1,Feature,...,Tp,Fp,Tn,Fn,Acc_0,Acc_1,Balanced_Acc,Precision,Recall,Fmeasure
0,Eclipse,knn,4,5804,2511,3293,1933,836,1097,Description,...,271,325,565,772,0.454698,0.422588,0.438643,0.454698,0.259827,0.330689
1,Eclipse,knn,8,5803,3075,2728,1934,1025,909,Description,...,572,466,453,443,0.551060,0.505580,0.528320,0.551060,0.563547,0.557233
2,Eclipse,knn,16,5803,3555,2248,1934,1185,749,Description,...,818,467,367,282,0.636576,0.565485,0.601031,0.636576,0.743636,0.685954
3,Eclipse,knn,32,5804,4085,1719,1933,1361,572,Description,...,1197,502,164,70,0.704532,0.700855,0.702693,0.704532,0.944751,0.807148
4,Eclipse,knn,64,5803,4612,1191,1934,1537,397,Description,...,1497,385,40,12,0.795430,0.769231,0.782331,0.795430,0.992048,0.882925
5,Eclipse,knn,128,5803,5055,748,1934,1685,249,Description,...,1671,247,14,2,0.871220,0.875000,0.873110,0.871220,0.998805,0.930660
6,Eclipse,knn,256,5804,5429,375,1933,1809,124,Description,...,1807,124,2,0,0.935785,1.000000,0.967892,0.935785,1.000000,0.966827
7,Eclipse,knn,512,5804,5697,107,1933,1898,35,Description,...,1898,35,0,0,0.981893,NaN,NaN,0.981893,1.000000,0.990864
8,Eclipse,rf,4,5804,2511,3293,1933,836,1097,Description,...,246,209,590,888,0.540659,0.399188,0.469924,0.540659,0.216931,0.309629
9,Eclipse,rf,8,5803,3075,2728,1934,1025,909,Description,...,682,503,343,406,0.575527,0.457944,0.516736,0.575527,0.626838,0.600088

In [8]:
%matplotlib inline

0.0184404636459431